name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
           docker build -t employeemanagement .
           docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}  
           docker tag employeemanagement kavisuresh/employeemanagement
           docker push kavisuresh/employeemanagement
